### ISSUE TITLE
Moire pattern appearing in MPC using FilmGrain1 after about 45 minutes

### ISSUE THREAD

**Issue by crolyss** [butterw/bShaders#2]
Using FilmGrain1.hlsl as pre-resize pixel shader a moire pattern appears all accross the screen. The screenshot shows this pattern which shows. After a minute or 2 it will vanish, but it is very distractinng during playback of video.

![02 mkv_snapshot_48 20_ 2023 03 21_00 01 29](https://user-images.githubusercontent.com/45496883/226382558-6014dd85-b4c6-4dcc-8d44-9bb300f0f697.png)

**Comment by butterw** [comment]
FilmGrain1.hlsl was a quick proof-of-concept attempt at porting mpv FilmGrain.glsl. 
The original mpv shader uses a random number between [0, 1.] provided by mpv. This doesn't exist in mpc-hc/be. As an alternative, the available clock value was used (time since the program was started in seconds, in floating-point) which seemed to work OK, but the shader wasn't tested extensively.

In short, if you couldn't find a workaround and it still doesn't work, don't use it as I'm not sure there is a simple fix. There are probably better alternatives.

**EDIT:** you could try (untested) changing the line in the shader defining random to:
#define random (frac(p0.w)) //Test using Clock instead of random, PRNG [0, 1.0]

**Comment by butterw** [comment]
I was able to reproduce the issue and my suggested fix seems to work.
v0.2: https://github.com/butterw/bShaders/blob/master/FilmGrain_Noise/FilmGrain1.hlsl

**Comment by crolyss** [comment]
Thanks very much for taking the time to try the fix it. I will try it out in the coming days and try to verify if it comes up again (for example another filter I used after this it happens after 2 and a half hours or so).
